# Generated by Django 4.2 on 2024-11-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridereservationparticipants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='carpool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.carpool'),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupridereservation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.carpool'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_carpools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpool',
            name='members',
            field=models.ManyToManyField(related_name='carpool_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
