# Generated by Django 4.2 on 2024-11-17 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('Baggage', models.BooleanField(default=False)),
                ('seat_count', models.IntegerField(help_text='Le nombre minimal de places doit être 1.', validators=[django.core.validators.MinValueValidator(1)])),
                ('Payment_Method', models.CharField(choices=[(' online_payment', ' online_payment'), ('cash_payment', 'cash_payment')], max_length=20)),
            ],
        ),
    ]
