# Generated by Django 4.2 on 2024-11-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_reclamation', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('en attente', 'En attente'), ('résolue', 'Résolue')], default='en attente', max_length=50)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='Trip.trajet')),
            ],
        ),
    ]
