# Generated by Django 4.2 on 2024-11-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclammation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='sujet',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='trajet',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('resolue', 'Résolue')], default='en_cours', max_length=50),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='titre',
            field=models.CharField(default='Default Title', max_length=200),
        ),
    ]
