# Generated by Django 4.2 on 2024-12-15 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reclammation', '0004_rename_description_reclamation_description_incident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseReclamationAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_penalite', models.CharField(blank=True, max_length=100, null=True)),
                ('score_analyse', models.FloatField(default=0.0)),
                ('validee', models.BooleanField(default=False)),
                ('date_analyse', models.DateTimeField(default=django.utils.timezone.now)),
                ('utilisateurcible', models.CharField(default='admin', max_length=100)),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='reclammation.reclamation')),
            ],
        ),
    ]
