# Generated by Django 4.2 on 2024-12-15 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reclammation', '0005_analysereclamationai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysereclamationai',
            name='utilisateurcible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
