# Generated by Django 4.2 on 2024-12-15 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reclammation', '0007_alter_analysereclamationai_utilisateurcible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysereclamationai',
            name='utilisateurcible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
