# Generated by Django 4.2 on 2024-12-15 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reclammation', '0008_alter_analysereclamationai_utilisateurcible'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseReclamationAvecAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_penalite', models.CharField(blank=True, max_length=100, null=True)),
                ('score_analyse', models.FloatField(default=0.0)),
                ('validee', models.BooleanField(default=False)),
                ('date_analyse', models.DateTimeField(default=django.utils.timezone.now)),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='reclammation.reclamation')),
                ('utilisateurcible', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AnalyseReclamationAI',
        ),
    ]
