# Generated by Django 4.2 on 2024-12-01 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_penalite', models.CharField(choices=[('annulation_tardive', 'Annulation Tardive'), ('harcelement', 'Harcèlement'), ('point_descente_faux', 'Point de descente incorrect'), ('nombre_places_incorrect', 'Nombre de places incorrect'), ('disponibilite_bagages_incorrecte', 'Disponibilité des bagages incorrecte'), ('paiement_non_effectue', 'Paiement non effectué')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_penalite', models.DateTimeField(auto_now_add=True)),
                ('gravite', models.IntegerField(choices=[(1, 'Mineure'), (2, 'Moyenne'), (3, 'Grave')], default=1)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('supprimer_compte', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
