# Generated by Django 4.2 on 2024-12-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalite',
            name='score_analyse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalite',
            name='validee',
            field=models.BooleanField(default=False),
        ),
    ]
