# Generated by Django 4.2 on 2024-12-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penality', '0003_alter_penalite_type_penalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalite',
            name='type_penalite',
            field=models.CharField(choices=[('annulation_tardive', 'Annulation Tardive'), ('Annulation_sans_informer', 'Annulation sans informer'), ('harcelement_et_mauvais_comportement', 'harcelement'), ('point_descente_faux', 'Point de descente incorrect'), ('nombre_places_incorrect', 'Nombre de places incorrect'), ('disponibilite_bagages_incorrecte', 'Disponibilité des bagages incorrecte'), ('paiement_non_effectue', 'Paiement non effectué'), ('others', 'others')], max_length=50),
        ),
    ]
