# Generated by Django 4.2 on 2024-12-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaire', '0004_commentaire_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='sentiment',
            field=models.CharField(blank=True, default='NEUTRAL', max_length=20, null=True),
        ),
    ]
