# Generated by Django 4.2 on 2024-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaire', '0007_remove_commentaire_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='langue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
